name: PR CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:   # <-- tombol manual

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    strategy:
      fail-fast: false
      matrix:
        flavor:
          - name: Standard
            artifactName: apk-standard
            gradleTask: assembleStandardDebug
            apkPath: app/build/outputs/apk/standard/debug/standard.apk
          - name: Ludashi
            artifactName: apk-ludashi
            gradleTask: assembleLudashiDebug
            apkPath: app/build/outputs/apk/ludashi/debug/ludashi.apk
          - name: Pubg
            artifactName: apk-pubg
            gradleTask: assemblePubgDebug
            apkPath: app/build/outputs/apk/pubg/debug/pubg.apk

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build APK
        run: |
          ./gradlew :app:${{ matrix.flavor.gradleTask }} --parallel

      - name: Prepare APK
        run: |
          mkdir -p artifacts/${{ matrix.flavor.artifactName }}
          cp ${{ matrix.flavor.apkPath }} \
             artifacts/${{ matrix.flavor.artifactName }}/app.apk

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.flavor.artifactName }}
          path: artifacts/${{ matrix.flavor.artifactName }}/*.apk